name: Build Godot Project

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  export_web:
    name: Export
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Build and export
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          use_preset_export_path: true
          export_debug: false

      - name: Upload web build to itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: ./export/web/Web.zip
          itchUsername: ${{ secrets.ITCH_USER }}
          itchGameId: ludumdare56
          buildChannel: html5

      # - name: Upload windows build to itch
      #   uses: KikimoraGames/itch-publish@v0.0.3
      #   with:
      #     butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
      #     gameData: ./export/win/win.zip
      #     itchUsername: ${{ secrets.ITCH_USER }}
      #     itchGameId: ludumdare56
      #     buildChannel: windows